site_name = "Data Foundations Project"
site_description = "A data foundations project repository for aaheid"
site_url = "https://github.io"
repo_url = "https://github.com"
repo_name = "aaheid/datafun-01-foundations"
site_dir = "site"

[[theme.social]]
icon = "fontawesome/brands/github"
link = "https://github.com"
